# Generated by Django 2.0.7 on 2018-07-26 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondBuyTransactionByHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('one_year', models.IntegerField()),
                ('one_to_three_years', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BondBuyTransactionByType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('treasury_bond', models.IntegerField()),
                ('policy_financial_bond', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BondNetTransactionByHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('one_year', models.IntegerField()),
                ('one_to_three_years', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BondNetTransactionByType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('treasury_bond', models.IntegerField()),
                ('policy_financial_bond', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BondSaleTransactionByHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('one_year', models.IntegerField()),
                ('one_to_three_years', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BondSaleTransactionByType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('treasury_bond', models.IntegerField()),
                ('policy_financial_bond', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='bondsaletransactionbytype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_sale_type', to='tasks.Organization'),
        ),
        migrations.AddField(
            model_name='bondsaletransactionbyholding',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_sale_holding', to='tasks.Organization'),
        ),
        migrations.AddField(
            model_name='bondnettransactionbytype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_net_type', to='tasks.Organization'),
        ),
        migrations.AddField(
            model_name='bondnettransactionbyholding',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_net_holding', to='tasks.Organization'),
        ),
        migrations.AddField(
            model_name='bondbuytransactionbytype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_buy_type', to='tasks.Organization'),
        ),
        migrations.AddField(
            model_name='bondbuytransactionbyholding',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_buy_holding', to='tasks.Organization'),
        ),
    ]
