# Generated by Django 2.0.7 on 2018-07-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondbuytransactionbyholding',
            name='one_to_three_years',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bondbuytransactionbyholding',
            name='one_year',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bondbuytransactionbytype',
            name='policy_financial_bond',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bondbuytransactionbytype',
            name='treasury_bond',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bondnettransactionbyholding',
            name='one_to_three_years',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bondnettransactionbyholding',
            name='one_year',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bondnettransactionbytype',
            name='policy_financial_bond',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bondnettransactionbytype',
            name='treasury_bond',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bondsaletransactionbyholding',
            name='one_to_three_years',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bondsaletransactionbyholding',
            name='one_year',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bondsaletransactionbytype',
            name='policy_financial_bond',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bondsaletransactionbytype',
            name='treasury_bond',
            field=models.FloatField(),
        ),
    ]
