# Generated by Django 2.0.7 on 2018-07-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180727_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
