# Generated by Django 2.0.7 on 2018-07-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180727_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryBondFutureMarketByTenYears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('security_name', models.CharField(max_length=256)),
                ('open_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('volume', models.FloatField()),
                ('amount', models.IntegerField()),
                ('change', models.FloatField()),
                ('percent_change', models.FloatField()),
                ('open_interest', models.FloatField()),
                ('open_interest_change', models.FloatField()),
            ],
        ),
    ]
